### ISSUE TITLE
RISE / Reveal integration

### ISSUE THREAD

**Issue by nicshub** [parmentelat/jupyterlab-gridwidth#17]
Hi @parmentelat , first of all thanks a lot for creating this extension.
I use jupyter for teaching and I didn't switch to Lab still since I used both RISE (now supported) and splitcell.
In presentation mode RISE managed splitcell to show cells using a "table" layout of two columns that coupled with fragment style is useful to compare two elements one by one.
Do you think is something it's possible to achieve with gridwith using css ?
Thanks

**Comment by nicshub** [comment]
I'm testing
`.cell-tag-gridwidth-1-2 {
  float: left;
  width: 50%;
}`

added in rise.css, works in Firefox (chrome seems blocking due to mime-types)

**Comment by parmentelat** [comment]
hey @nicshub 

I have been a rather heavy user of RISE myself and have even acted as a maintainer at some point; however over time I must admit have lost interest, so I have not followed the move to jupyterlab-rise

regardless, I'd like to outline that

- the actual css recipe that the extension uses is this one
  https://github.com/parmentelat/jupyterlab-gridwidth/blob/main/style/base.css
  as I'm sure you've figured
- I guess this css is not getting injected automatically in the rise preview pane, and this I think is because my extension only targets the notebook pane specifically; you could though consider injecting it - or a variation of it - in your `rise.css`, like you are doing
- just note that in my css, I set the root of all cells with `display: flex` 
  https://github.com/parmentelat/jupyterlab-gridwidth/blob/main/style/base.css#L20-L25
  which IIRC is rather crucial to achieving the desired layout
- maybe your version of the css will need to be tweaked for the rise preview because of this nested rule
https://github.com/parmentelat/jupyterlab-gridwidth/blob/main/style/base.css#L18
- also the `float: left;` sounds a little off in this context, but that's totally second order

I have no idea though as to why the 2 browsers could behave differently; I take it you've hard-reloaded everything before reaching that conclusion ? 

hope this helps

**Comment by nicshub** [comment]
Thanks @parmentelat
I think that I will use a combination of Jupyter Lab, Myst and Quarto (and gridwith) for the new academic year.
unfortunately Rise did not follow the changes.

**Comment by giovannibarbarino** [comment]
For anybody interested, this works for me (when added to `rise.css`). Works in Chrome.

```
.cell-tag-gridwidth-1 { 
	display: block;
    width: 100vw; }

.cell-tag-gridwidth-1-2 { 
	display: flex !important;
    flex-direction: row;
    flex-wrap: wrap;
    align-items: flex-start;
    min-width: 200px;
    width: 50vw; }
    
.cell-tag-gridwidth-1-3 { 
	display: flex !important;
    flex-direction: row;
    flex-wrap: wrap;
    align-items: flex-start;
    min-width: 200px;
    width: 33vw; }
    
.fragment, .present{ 
	display: flex !important;
	flex-direction: row;
    flex-wrap: wrap;
    align-items: flex-start;
	} 
```


"gridwidth-1" is a tag I add manually to all cells not splitted. 
You can probably use a version with `:not` to exclude all splitted cells.
Also, I only used gridwidth 1-2 and 1-3, but the rest are analogous, just use the right amount of vw.

**Comment by laowantong** [comment]
Under JupyterLab with jupyterlab-rise and jupyterlab-gridwidth, this code cell at the start of the notebook did the trick:
```css
%%HTML
<style>
[class*="cell-tag-gridwidth-"] {
  box-sizing: border-box;
  float: left;
  display: block;
}

.jp-Cell:not([class*="cell-tag-gridwidth-"]) {
  clear: both;
}

.cell-tag-gridwidth-1-2 { width: 50%; }
.cell-tag-gridwidth-1-3 { width: 33.3%; }
.cell-tag-gridwidth-2-3 { width: 66.6%; }
.cell-tag-gridwidth-1-4 { width: 25%; }
.cell-tag-gridwidth-3-4 { width: 75%; }
.cell-tag-gridwidth-1-5 { width: 20%; }
.cell-tag-gridwidth-2-5 { width: 40%; }
.cell-tag-gridwidth-3-5 { width: 60%; }
.cell-tag-gridwidth-4-5 { width: 80%; }
</style>
```
